crash_course/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("",include("todo.urls")),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from .views import todo_list,todo_detail,todo_create,todo_update,todo_delete


app_name = "todos"

urlpatterns = [
  path("",todo_list,name="todo_list"),
  path("details/<int:id>",todo_detail,name="todo_detail"),
  path("create",todo_create,name="todo_create"),
  path("update/<int:id>",todo_update,name="todo_update"),
  path("delete/<int:id>",todo_delete,name="todo_delete"),
]

todo/models.py
from django.db import models

# Create your models here.
# model in django is inherited from the models.model each models refer to the table in database 
class todo(models.Model):
    name = models.CharField(max_length=100)
    due_date = models.DateField()

    def __str__(self):
        return self.name

todo/forms.py
from django import forms 
from .models import todo

class Todo_form(forms.ModelForm):

    class Meta:
        model = todo
        fields = ['name','due_date']

todo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import todo
from .forms import Todo_form

# Create your views here.
# views are used for handing the request it handle request and execute business logic as well as retuen response
def todo_list(request):
    todos = todo.objects.all()
    context = {
        "todos" : todos
    }
    return render(request,"index.html",context)

def todo_detail(request,id):
    todo_item = todo.objects.get(id=id)
    context = {
        "todo_item" : todo_item
    }
    return render(request,"todo_detail.html",context)

def todo_create(request):
    form  = Todo_form(request.POST or None)
    if form.is_valid():
        # name = form.cleaned_data['name']
        # due_date = form.cleaned_data['due_date']
        # todo_form = todo.objects.create(name = name,due_date = due_date)
        # todo_form.save()
        form.save()
        return redirect("/")
    context = {
        "form" : form
    }
    return render(request,"todo_create.html",context)

def todo_update(request,id):
    todo_item = todo.objects.get(id=id)
    form = Todo_form(request.POST or None,instance=todo_item)
    if form.is_valid():
        form.save()
        return redirect("/")
    context = {
        "form" : form
    }
    return render(request,"todo_update.html",context)

def todo_delete(request,id):
    todo_item = todo.objects.get(id=id)
    todo_item.delete()
    return redirect("/")

    

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Todo List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'todos:todo_create' %}"> create todo </a>
    {% if request.user.is_authenticated %}
        hello {{ request.user.username }}
    {% else %}
        hello anynomus 
    {% endif %}
    {% for todo in todos %}
      <li><a href="{% url 'todos:todo_detail' todo.id %}"> {{ todo.name }} it's due date {{ todo.due_date }} </li> </a> 
      <a href="{% url 'todos:todo_update' todo.id %}">update </a>
      <a href="{% url 'todos:todo_delete' todo.id %}">Delete </a>
    {% endfor %}
{% endblock content %}

templates/todo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="col-4 offset-4">
    <h4>Create a todo</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">SUBMIT</button>
    </form>
{% endblock content%}

templates/todo_detail.html
{% extends 'base.html' %}
{% block content %}
    {{ todo_item.name  }}
    {{ todo_item.due_date  }}
{% endblock content%}

templates/todo_update.html
{% extends 'base.html' %}
{% block content%}
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">SUBMIT</button>
    </form>
{% endblock content %}